import { createFileRoute } from "@tanstack/react-router";
import { ChartNoAxesCombined, Compass, Sprout } from "lucide-react";
import { BrightlyNav } from "@/components/brightly-nav";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/invest")({
  head: () => ({ meta: [{ title: "Invest with Brightly — A future-focused money pot" }, { name: "description", content: "Brightly makes it simple to start a future money pot alongside your child’s everyday savings." }, { property: "og:title", content: "Invest with Brightly — A future-focused money pot" }, { property: "og:description", content: "Brightly makes it simple to start a future money pot alongside your child’s everyday savings." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: InvestPage,
});

function InvestPage() {
  return <main className="min-h-screen overflow-hidden bg-background"><section className="relative bg-[oklch(0.79_0.13_112)] px-6 pb-24 pt-5 text-[oklch(0.2_0.08_133)] lg:px-16"><div className="absolute right-[10%] top-36 h-40 w-40 rounded-full border-[22px] border-[oklch(0.94_0.08_105)]" /><div className="relative mx-auto max-w-[1440px]"><BrightlyNav active="invest" tone="light" /><div className="max-w-3xl pt-20"><p className="text-sm font-black uppercase tracking-[0.17em] text-[oklch(0.37_0.12_132)]">For the future</p><h1 className="mt-5 text-5xl font-black leading-tight sm:text-6xl">Plant small seeds for big tomorrows.</h1><p className="mt-7 max-w-2xl text-xl leading-relaxed">Open a simple future pot alongside their everyday money habits, and help them see how time can do some of the growing.</p><Button className="mt-9 h-14 rounded-full bg-primary px-9 text-primary-foreground">Get started</Button></div></div></section><section className="px-6 py-20 lg:px-16"><div className="mx-auto max-w-6xl"><h2 className="max-w-2xl text-4xl font-black leading-tight sm:text-5xl">A calm place to look ahead.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{[[Sprout, "Start simply", "Set up a future pot with an amount that works for you."], [ChartNoAxesCombined, "See the picture", "Track contributions and learn why long-term choices can matter."], [Compass, "Keep perspective", "Use plain language to talk about ups, downs and time."]].map(([Icon, title, copy]) => { const FeatureIcon = Icon as typeof Sprout; return <article key={title as string} className="rounded-lg bg-card p-7 shadow-sm"><FeatureIcon className="h-9 w-9 text-[oklch(0.52_0.15_132)]" /><h3 className="mt-6 text-2xl font-black">{title as string}</h3><p className="mt-3 leading-relaxed text-muted-foreground">{copy as string}</p></article>})}</div><p className="mt-12 text-sm text-muted-foreground">The value of a future pot can go down as well as up. Brightly’s tools are for learning and planning, not personal financial advice.</p></div></section></main>;
}