import { createFileRoute, Link } from "@tanstack/react-router";
import { Check } from "lucide-react";
import { BrightlyNav } from "@/components/brightly-nav";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/pricing")({
  head: () => ({ meta: [{ title: "Plans & pricing — Brightly" }, { name: "description", content: "Choose a Brightly plan that makes room for everyday money learning." }, { property: "og:title", content: "Plans & pricing — Brightly" }, { property: "og:description", content: "Choose a Brightly plan that makes room for everyday money learning." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: PricingPage,
});

function PricingPage() {
  return <main className="min-h-screen overflow-hidden bg-background"><section className="bg-[oklch(0.57_0.23_292)] px-6 pb-24 pt-5 text-primary-foreground lg:px-16"><div className="mx-auto max-w-[1440px]"><BrightlyNav active="pricing" /><div className="mx-auto max-w-3xl pb-3 pt-20 text-center"><p className="text-sm font-black uppercase tracking-[0.17em] text-[oklch(0.86_0.1_292)]">Plans that grow with them</p><h1 className="mt-5 text-5xl font-black leading-tight sm:text-6xl">A brighter way to start.</h1><p className="mt-6 text-xl leading-relaxed text-[oklch(0.96_0.02_292)]">All the tools to help young people earn, save, spend and learn with confidence.</p></div></div></section><section className="px-6 py-20 lg:px-16"><div className="mx-auto grid max-w-5xl gap-5 md:grid-cols-2">{[["Brightly Everyday", "£2.99", ["One young person", "Earn, save and spend tools", "Parent activity view"]], ["Brightly Together", "£4.99", ["Up to four young people", "Everything in Everyday", "Extra saving goal support"]]].map(([name, price, benefits], index) => <article key={name as string} className={`rounded-lg border p-8 ${index === 1 ? "border-[oklch(0.61_0.19_292)] bg-card shadow-xl" : "bg-card"}`}><p className="text-sm font-black uppercase tracking-[0.14em] text-muted-foreground">{index === 1 ? "Most popular" : "For getting started"}</p><h2 className="mt-4 text-3xl font-black">{name as string}</h2><p className="mt-5 text-5xl font-black">{price as string}<span className="text-base text-muted-foreground"> / month</span></p><ul className="mt-8 grid gap-4">{(benefits as string[]).map((benefit) => <li key={benefit} className="flex gap-3"><Check className="h-5 w-5 text-[oklch(0.55_0.17_173)]" />{benefit}</li>)}</ul><Link to="/signup" className="mt-9 inline-flex h-12 w-full items-center justify-center rounded-full bg-primary px-6 font-bold text-primary-foreground hover:bg-primary/90">Choose this plan</Link></article>)}</div></section><section className="bg-accent px-6 py-14 text-accent-foreground"><div className="mx-auto flex max-w-5xl flex-col justify-between gap-5 sm:flex-row sm:items-center"><h2 className="text-3xl font-black">Not sure where to start?</h2><Button className="rounded-full bg-primary px-8 text-primary-foreground">See how Brightly works</Button></div></section></main>;
}