import { createFileRoute, Link } from "@tanstack/react-router";
import { Check } from "lucide-react";
import { BrightlyNav } from "@/components/brightly-nav";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/signup")({
  head: () => ({ meta: [{ title: "Get started — Brightly" }, { name: "description", content: "Create your Brightly family space and start building money confidence together." }, { property: "og:title", content: "Get started — Brightly" }, { property: "og:description", content: "Create your Brightly family space and start building money confidence together." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: SignupPage,
});

function SignupPage() { return <main className="min-h-screen bg-background px-6 pt-5"><div className="mx-auto max-w-[1440px]"><BrightlyNav tone="light" /></div><section className="mx-auto grid max-w-5xl gap-16 py-20 lg:grid-cols-[1fr_0.85fr]"><div><p className="text-sm font-black uppercase tracking-[0.16em] text-[oklch(0.59_0.17_292)]">Let’s get started</p><h1 className="mt-4 text-5xl font-black leading-tight sm:text-6xl">A bright beginning for every money story.</h1><ul className="mt-8 grid gap-4 text-lg">{["Create a family space in a few minutes", "Choose the features that fit your family", "Start their first goal together"].map((item) => <li key={item} className="flex gap-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-accent"><Check size={16} /></span>{item}</li>)}</ul></div><form className="rounded-lg bg-card p-7 shadow-xl"><h2 className="text-2xl font-black">Create your account</h2><label className="mt-6 block text-sm font-bold" htmlFor="signup-email">Email address</label><input id="signup-email" type="email" className="mt-2 h-12 w-full rounded-md border bg-background px-4" placeholder="you@example.com" /><label className="mt-5 block text-sm font-bold" htmlFor="signup-password">Choose a password</label><input id="signup-password" type="password" className="mt-2 h-12 w-full rounded-md border bg-background px-4" placeholder="At least 8 characters" /><Button type="button" className="mt-7 h-12 w-full rounded-full bg-primary text-primary-foreground">Create account</Button><p className="mt-6 text-sm text-muted-foreground">Already have an account? <Link to="/login" className="font-bold text-foreground underline">Sign in</Link></p></form></section></main>; }