/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LearnLessonIdRouteImport } from './routes/learn.$lessonId'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SaveRouteImport } from './routes/save'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SpendRouteImport } from './routes/spend'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLessonIdRoute = LearnLessonIdRouteImport.update({
  id: '/learn/$lessonId',
  path: '/learn/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SaveRoute = SaveRouteImport.update({
  id: '/save',
  path: '/save',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SpendRoute = SpendRouteImport.update({
  id: '/spend',
  path: '/spend',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/earn': typeof EarnRoute
  '/invest': typeof InvestRoute
  '/learn': typeof LearnRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/save': typeof SaveRoute
  '/signup': typeof SignupRoute
  '/spend': typeof SpendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/earn': typeof EarnRoute
  '/invest': typeof InvestRoute
  '/learn': typeof LearnRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/save': typeof SaveRoute
  '/signup': typeof SignupRoute
  '/spend': typeof SpendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/earn': typeof EarnRoute
  '/invest': typeof InvestRoute
  '/learn': typeof LearnRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/save': typeof SaveRoute
  '/signup': typeof SignupRoute
  '/spend': typeof SpendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/earn'
    | '/invest'
    | '/learn'
    | '/learn/$lessonId'
    | '/login'
    | '/pricing'
    | '/save'
    | '/signup'
    | '/spend'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/earn'
    | '/invest'
    | '/learn'
    | '/learn/$lessonId'
    | '/login'
    | '/pricing'
    | '/save'
    | '/signup'
    | '/spend'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/earn'
    | '/invest'
    | '/learn'
    | '/learn/$lessonId'
    | '/login'
    | '/pricing'
    | '/save'
    | '/signup'
    | '/spend'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EarnRoute: typeof EarnRoute
  InvestRoute: typeof InvestRoute
  LearnRoute: typeof LearnRoute
  LearnLessonIdRoute: typeof LearnLessonIdRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SaveRoute: typeof SaveRoute
  SignupRoute: typeof SignupRoute
  SpendRoute: typeof SpendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$lessonId': {
      id: '/learn/$lessonId'
      path: '/learn/$lessonId'
      fullPath: '/learn/$lessonId'
      preLoaderRoute: typeof LearnLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/save': {
      id: '/save'
      path: '/save'
      fullPath: '/save'
      preLoaderRoute: typeof SaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spend': {
      id: '/spend'
      path: '/spend'
      fullPath: '/spend'
      preLoaderRoute: typeof SpendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EarnRoute: EarnRoute,
  InvestRoute: InvestRoute,
  LearnRoute: LearnRoute,
  LearnLessonIdRoute: LearnLessonIdRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SaveRoute: SaveRoute,
  SignupRoute: SignupRoute,
  SpendRoute: SpendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
